# -*- coding: utf-8 -*-
"""2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u2T1LZ5OLoExUaaRuKaiOaYbwU5-4sqo
"""

point = input()
character = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
initial_x = character.index(point[0]) + 1
# code in the book
# initial_x = ord(point[0]) - ord('a') + 1

initial_y = int(point[1])

move = [[-1, -2], [1, -2], [2, -1], [2, 1], [1, 2], [-1, 2], [-2, 1], [-2, -1]]

result = 0

for i in range(8):
  x = initial_x + move[i][0]
  y = initial_y + move[i][1]
  if (1 <= x) and (x <= 8) and (1 <= y) and (y <= 8):
    result += 1

print(result)