# -*- coding: utf-8 -*-
"""CodeInterviewQ02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FHrmu0k52UwtYH8HK135-UB6Wu3xAbj6
"""

# numbers = list(map(int, input().split()))
numbers = input()
result = int(numbers[0])

for i in range(1, len(numbers)):
  num = int(numbers[i])
  if num <= 1 or result <= 1:
    result += num
  else:
    result *= num

print(result)

# for i in range(1, len(numbers)):
#   if numbers[i] == 0 or numbers[i] == 1:
#     result += numbers[i]
#   else:
#     if result == 0 or numbers[i] == 1:
#       result += numbers[i]
#     else:
#       result *= numbers[i]

# print(result)