# -*- coding: utf-8 -*-
"""CodeInterviewQ01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xi6rHDGF0tX5h7WBvcibkeRLfSfxM6FD
"""

n = int(input())

fear = list(map(int, input().split()))
fear.sort()

s, e = 0, 0
groups = 0

while (s < n-1):
  e = s + fear[s] - 1
  if (e > n): break
  if (e - s + 1 == fear[e]):
    groups += 1
    s = e + 1
  else:
    while (e - s + 1 != fear[e]):
      e = s + fear[e] - 1
      if (e > n-1): break
    if (e > n-1): break
    groups += 1
    s = e + 1

print(groups)

"""1st : 47min

Solution
"""

n = int(input())
data = list(map(int, input()))
data.sort()

result = 0 # number of groups
count = 0 # number of adventurer in current group

for i in data:
  count += 1
  if count >= i:
    result += 1
    count = 0

print(result)