# -*- coding: utf-8 -*-
"""Q05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15M7kiSUVohjSx1VJBw6GcV5EM1HRf04e
"""

n, m = map(int, input().split())
weights = list(map(int, input().split()))

cnt = 0
numbers = [0 for _ in range(m)]

# 1 <= m <= 10
array = [0] * 11

for x in weights:
  array[x] += 1

for i in range(1, m):
  n -= array[i]
  cnt += array[i] * n

print(cnt)

########################
# enhanced poor answer #
########################

# for i in range(n):
#   numbers[weights[i] - 1] += 1

# for i in range(m-1):
#   a = numbers[i]
#   for j in range(i+1, m):
#     cnt += a * numbers[j]

# print(cnt)

###############
# poor answer #
###############

# for i in range(len(weights)-1):
#   a = weights[i]
#   for j in range(i+1, len(weights)):
#     if weights[j] != a:
#       cnt += 1

# print(cnt)